export default {
    CHANGE_PAGE_EVENT: "CHANGE_PAGE_EVENT",
    PAGE_DASHBOARD: "PAGE_DASHBOARD",
    PAGE_SAVINGS: "PAGE_SAVINGS",
    PAGE_REPORTS: "PAGE_REPORTS",
    PAGE_SETTINGS: "PAGE_SETTINGS",
    SENSOR_UPDATE: "SENSOR_UPDATE",
    HOT_SENSOR_UPDATE: "HOT_SENSOR_UPDATE",
    COLD_SENSOR_UPDATE: "COLD_SENSOR_UPDATE",
    STATS_UPDATE: "STATS_UPDATE",
    COLD_ALERTS_UPDATE: "COLD_ALERTS_UPDATE",
    HOT_ALERTS_UPDATE: "HOT_ALERTS_UPDATE",
    LIMITS_UPDATE: "LIMITS",

    LIMITS_GET: "LIMITS_GET",
    LIMITS_SET: "LIMITS_SET",

    DAILY_STATUS: "DAILY_STATUS",
    MONTHLY_STATUS: "MONTHLY_STATUS",
    MONTHLY_STATS: "MONTHLY_STATS"
}
